# Generated by Django 5.1.4 on 2024-12-21 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('output_file', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanMaster',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('pan_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('bank_account_number', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=255)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allloans.analysis')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allloans.loanmaster')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_acquired_time', models.DateTimeField()),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allloans.loanmaster')),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allloans.loanmaster'),
        ),
    ]
